# Site settings
title: Hugues Absil
email: h.absil@hotmail.fr
description: > # this means to ignore newlines until "baseurl:"
  Peintre, et lithographe français.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hugues-absil.com" # the base hostname & protocol for your site
twitter_username: 
github_username:

paginate: 5
paginate_path: "/:num/"

# Build settings
markdown: kramdown

# Pretty URL
#permalink: "posts/:title"

# Custom categories
categories: [navbar]

collections:
  galeries:
    output: true
  courshistoire:
    output: true
    permalink: /cours/histoire-art/:path/
  courstechnique:
    output: true
    permalink: /cours/technique-art/:path/

sass:
    style: compressed

gems: [jekyll-paginate]
